# Site settings
name: Damonrain
email: yuying_ruc@163.com
author: Damonrain
url: https://damonrain.github.io/
github: https://github.com/Damonrain
baseurl: ""
description: 永远充满好奇，永远热泪盈眶。
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Damonrain

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

